apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: exclusive-placement
  annotations:
    alpha.jobset.sigs.k8s.io/exclusive-topology: cloud.google.com/gke-nodepool # 1:1 job replica to node pool assignment
spec:
  failurePolicy:
    maxRestarts: 3
  replicatedJobs:
  - name: workers
    replicas: 3 # set to number of node pools
    template:
      spec:
        parallelism: 1998
        completions: 1998
        backoffLimit: 0
        template:
          spec:
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                  - matchExpressions:
                    - key: cloud.google.com/gke-nodepool
                      operator: NotIn
                      values:
                      - heapster-pool
            containers:
            - name: sleep
              image: bash:latest
              command: 
                - bash
                - -xc
                - |
                  echo "starting up"
                  sleep 1000
