apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: failurepolicy
spec:
  failurePolicy:
    maxRestarts: 0
    rules:
      - action: RestartJobSetAndIgnoreMaxRestarts 
        targetReplicatedJobs:
        - leader
        onJobFailureReasons:
        - PodFailurePolicy
  replicatedJobs:
  - name: leader
    replicas: 1
    template:
      spec:
        # Set backoff limit to 0 so job will immediately fail if any pod fails.
        backoffLimit: 0
        completions: 2
        parallelism: 2
        template:
          spec:
            restartPolicy: Never
            containers:
            - name: leader
              image: bash:latest
              command:
              - bash
              - -xc
              - |
                for i in $(seq 1 1000)
                do
                  echo "$i"
                  sleep 1
                done
        podFailurePolicy:
          rules:
          - action: FailJob
            onPodConditions:
            - type: DisruptionTarget